language: node_js
node_js:
  - '4.1'
install:
  - npm install
script: "npm run build"

deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "test.princessnokia.org"
  skip_cleanup: true
  local_dir: dist
