language: node_js
node_js:
  - '4.1'
install:
  - npm install
script:
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh

deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "dev.princessnokia.org"
  skip_cleanup: false